title: Digital Archives - HIST-GA-1011
description: Syllabus and course materials for Digital Archives - HIST-GA-1011 (Spring 2024)
theme: just-the-docs

url: https://digital-archives.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

aux_links_new_tab: true
