title: Digital Archives - HIST-GA-1011
description: Syllabus and course materials for Digital Archives - HIST-GA-1011 (Spring 2024)
theme: just-the-docs

url: https://digital-archives.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

aux_links_new_tab: true

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
      
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
