name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Remove Old Cache Manually
        run: |
          rm -rf vendor/bundle
          rm -rf ~/.bundle
          rm -rf ~/.gem
          rm -rf .jekyll-cache
          rm -rf .sass-cache
          rm -rf Gemfile.lock  # Force fresh install
          echo "cache-bust=$(date +%s)" >> $GITHUB_ENV

      - name: Setup Ruby (Force 3.2.2)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false  # Prevent caching issues

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler:2.5.9
          bundle install --no-cache

      - name: Build with Jekyll
        run: bundle exec jekyll build
