name: Deploy Jekyll Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove Old Cache Manually & Clear `_site/`
        run: |
          rm -rf vendor/bundle
          rm -rf ~/.bundle
          rm -rf ~/.gem
          rm -rf .jekyll-cache
          rm -rf .sass-cache
          rm -rf Gemfile.lock  # Force fresh install
          rm -rf _site  # This ensures a clean rebuild
          echo "cache-bust=$(date +%s)" >> $GITHUB_ENV      

      - name: Setup Ruby (Force 3.2.2)
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: false

      - name: Install Bundler and Dependencies
        run: |
          gem install bundler:2.5.9
          bundle install --no-cache

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          publish_branch: gh-pages
